name: Feature Request
description: Suggest an idea for this project
title: "[Feature Request]: "
labels: ["enhancement"]
assignees:
  - cerimorse
body:
  - type: markdown
    attributes: 
      value: |
        Please search to see if an issue already exists before opening a feature request.

        ---

        Thank you for taking the time to file a feature request. Please provide as much of the information below as possible to help me understand the request:
  - type: textarea
    id: feature-description
    attributes:
      label: Feature description
      description: A clear and concise description of what you want to happen.
    validations:
      required: true