import "@/app/styles/globals.css";

import { Rubik } from "next/font/google";
import { cn } from "@/app/lib/utils";
import ThemeProvider from "@/app/providers/theme-provider";

const rubik = Rubik({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  themeColor: [
    { media: "(prefers-color-scheme: light)", color: "white" },
    { media: "(prefers-color-scheme: dark)", color: "black" },
  ],
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" suppressHydrationWarning>
      <head />
      <body
        className={cn(
          "min-h-screen bg-background antialiased",
          rubik.className
        )}
      >
        <ThemeProvider attribute="class" defaultTheme="system" enableSystem>
          <div className="bg-background min-h-screen"></div>
          {children}
        </ThemeProvider>
      </body>
    </html>
  );
}
