import "./globals.css";
import { Rubik } from "next/font/google";
import { cn } from "@/app/lib/utils";

const rubik = Rubik({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={cn("dark", rubik.className)}>{children}</body>
    </html>
  );
}
